const {chromium}=require('playwright');const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
const port=4197,server=http.createServer((req,res)=>{try{let p=path.join(path.resolve(__dirname,'../dist'),decodeURIComponent(req.url.split('?')[0]));if(req.url==='/')p+='/index.html';res.setHeader('Content-Type',{'.js':'text/javascript','.css':'text/css','.html':'text/html'}[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p))}catch{res.writeHead(404);res.end()}});
const captureDir=process.env.CAPTURE_DIR||'/tmp/beznogim-world-tests';fs.mkdirSync(captureDir,{recursive:true});
(async()=>{await new Promise(r=>server.listen(port,'127.0.0.1',r));const mobile=process.argv[2]==='mobile',name=mobile?'mobile':'desktop';const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox','--use-angle=swiftshader','--enable-webgl','--enable-unsafe-swiftshader','--single-process','--no-zygote']});const page=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1200,height:900},isMobile:mobile,hasTouch:mobile});page.setDefaultTimeout(20000);const errors=[],requests=[];page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>requests.push(r.url()));const snap=()=>page.evaluate(()=>__yard.inspect());
const click=async sel=>{const l=page.locator(sel);await l.scrollIntoViewIfNeeded();const b=await l.boundingBox();assert(b,sel);const x=b.x+b.width/2,y=b.y+b.height/2;assert(await page.evaluate(({sel,x,y})=>document.querySelector(sel).contains(document.elementFromPoint(x,y)),{sel,x,y}),sel+' overlapped');mobile?await page.touchscreen.tap(x,y):await page.mouse.click(x,y);};
await page.goto(`http://127.0.0.1:${port}/`,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__yard);await page.waitForTimeout(500);
// A real map/card portal, not programmatic selection.
await click('#territory-map');await click('[data-sector="1:0"]');await page.waitForFunction(()=>__yard.inspect().territory.sector==='1:0');await page.waitForTimeout(700);await click('.hotspot[data-label="сырный погреб"]');await click('#focus-object');await page.waitForTimeout(700);let before=await snap();await click('#enter-dream02');await page.waitForFunction(()=>__yard.inspect().dreamId===2);assert.equal((await snap()).sleepDream.rootVisible,false);await page.screenshot({path:`${captureDir}/dream02-start-${name}.png`});
for(let i=1;i<=3;i++){await click('#dream-breathe');await page.waitForFunction(i=>__yard.inspect().sleepDream.phase>i-.08,i);assert.equal((await snap()).sleepDream.step,i);await page.screenshot({path:`${captureDir}/dream02-step${i}-${name}.png`});}
let completed=await snap();assert(completed.sleepDream.waterY>.44);assert.equal(completed.sleepDream.droplets,16);assert.equal(completed.sleepDream.trace,true);assert.equal(await page.locator('#dream-breathe').textContent(),'увидеть сон снова');await click('#dream-breathe');await page.waitForFunction(()=>__yard.inspect().sleepDream.step===0);await click('#exit-dream');await page.waitForFunction(()=>__yard.inspect().dreamId===null);let back=await snap();assert.deepEqual(back.target,before.target);assert.equal(back.zoom,before.zoom);assert.equal(back.sleepDream.rootVisible,true);assert.equal(back.cellar.cutCount,before.cellar.cutCount);
// Archive preserves dream01, its real actions still work.
await click('#dream-archive');await click('[data-dream-id="1"]');await page.waitForFunction(()=>__yard.inspect().greenhouse.dream);for(let i=0;i<3;i++)await click('#dream-breathe');await page.waitForFunction(()=>__yard.inspect().greenhouse.phase>2.9);await page.screenshot({path:`${captureDir}/dream01-archive-${name}.png`});await page.keyboard.press('Escape');await page.waitForFunction(()=>__yard.inspect().dreamId===null);
await click('#dream-archive');await click('[data-dream-id="2"]');await page.waitForFunction(()=>__yard.inspect().sleepDream.active);await click('#rotate');await click('#zoom-in');await click('#home');await page.waitForFunction(()=>__yard.inspect().dreamId===null);assert.equal((await snap()).sleepDream.rootVisible,true);
// Warm and repeat 4 completed dreams, no per-entry geometry allocation.
await click('#dream-archive');await click('[data-dream-id="2"]');for(let i=0;i<3;i++)await click('#dream-breathe');await page.waitForFunction(()=>__yard.inspect().sleepDream.phase>2.9);let geos=(await snap()).gpuGeometries;await click('#exit-dream');for(let j=0;j<4;j++){await click('#dream-archive');await click('[data-dream-id="2"]');for(let i=0;i<3;i++)await click('#dream-breathe');await page.waitForFunction(()=>__yard.inspect().sleepDream.phase>2.9);assert.equal((await snap()).gpuGeometries,geos);await click('#exit-dream');}
await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>__yard.inspect().sleepDream.trace);assert.equal((await snap()).dreamId,null);
if(mobile){await page.setViewportSize({width:390,height:650});await click('#dream-archive');await click('[data-dream-id="2"]');for(let i=0;i<3;i++)await click('#dream-breathe');await page.waitForFunction(()=>__yard.inspect().sleepDream.phase>2.9);await page.screenshot({path:path.join(captureDir,'dream02-short-mobile.png')});await click('#exit-dream');}
assert.equal(errors.length,0,errors.join('\n'));assert.equal(requests.filter(u=>!u.startsWith(`http://127.0.0.1:${port}`)).length,0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth||document.documentElement.scrollHeight>innerHeight),false);
fs.writeFileSync(`${captureDir}/dream02-results-${name}.json`,JSON.stringify({passed:true,checks:['real map/card portal','3 transformed states','replay','button/Escape/Home exit','camera restore','old dream01 archive/actions','unchanged cellar','persistent trace','4 full cycles stable GPU','no overflow/errors/external'],geos,before,completed,errors},null,2));console.log('PASS dream02',name);await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});
