// Explicit read-only transport fixture; not production and not a claim of agent behaviour.
const {chromium}=require('playwright');const fs=require('fs'),path=require('path'),assert=require('assert');
const captureDir=process.env.CAPTURE_DIR||'/tmp/beznogim-world-tests';fs.mkdirSync(captureDir,{recursive:true});
(async()=>{const mobile=process.argv[2]==='mobile',name=mobile?'mobile':'desktop';const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox','--use-angle=swiftshader','--enable-webgl','--enable-unsafe-swiftshader','--single-process','--no-zygote']});const page=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1200,height:900},isMobile:mobile,hasTouch:mobile});const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.setDefaultTimeout(20000);
const t=Date.now()/1000;const history=[{id:1,time:t-1,type:'wait',text:'начал долгий сон до утра'},{id:2,time:t,type:'muse',text:'это тестовая публичная мысль'}];
const snapshot={version:1,server_time:t,heartbeat:t,resident_status:'sleeping',position:[-.15,1.9,.85],objects:{},release:{commit:'explicit-sleep-browser-fixture'},action:{kind:'sleep',started:t,ends:t+8*3600,label:'спит до 12:00 МСК'},history};
await page.addInitScript(()=>{window.EventSource=class extends EventTarget{constructor(){super();window.__sleepTransport=this;}}});
await page.route('https://head.alesha.pro/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/api/state')return route.fulfill({json:snapshot});if(u.pathname==='/api/history')return route.fulfill({json:{entries:history,has_more:false}});try{const p=path.join(path.resolve(__dirname,'../dist'),u.pathname==='/'?'index.html':u.pathname);return route.fulfill({body:fs.readFileSync(p),contentType:{'.js':'text/javascript','.css':'text/css','.html':'text/html'}[path.extname(p)]||'application/octet-stream'});}catch{return route.fulfill({status:404,body:''})}});
const click=async sel=>{const l=page.locator(sel);await l.scrollIntoViewIfNeeded();const b=await l.boundingBox();assert(b,sel);const x=b.x+b.width/2,y=b.y+b.height/2;assert(await page.evaluate(({sel,x,y})=>document.querySelector(sel).contains(document.elementFromPoint(x,y)),{sel,x,y}),sel+' overlap');mobile?await page.touchscreen.tap(x,y):await page.mouse.click(x,y);};
const snap=()=>page.evaluate(()=>__yard.inspect());async function emit(patch){await page.evaluate(patch=>{const d={...window.__beznogimState,...patch};window.__sleepTransport.dispatchEvent(new MessageEvent('state',{data:JSON.stringify(d)}));},patch);}
await page.goto('https://head.alesha.pro/',{waitUntil:'networkidle'});await page.waitForFunction(()=>__yard.inspect().sleepBody.visible);assert.equal(await page.locator('.resident-status').textContent(),snapshot.action.label);assert.deepEqual((await snap()).resident.position,snapshot.position);assert.equal((await snap()).sleepBody.ends,snapshot.action.ends);
// UI focus uses the real body; no teleport or wake tool.
await click('.resident-strip button:first-of-type');await page.waitForTimeout(1100);await page.screenshot({path:`${captureDir}/resident-sleep-fixture-${name}.png`});
const mode='.resident-strip button:nth-of-type(2)';await click(mode);await page.waitForFunction(()=>!__yard.inspect().sleepBody.visible);assert.equal(await page.evaluate(()=>__beznogimState.action.kind),'sleep');await click(mode);await page.waitForFunction(()=>__yard.inspect().sleepBody.visible);
// Persisted sleeping snapshot reload does not call sleep/cancel/write endpoints.
await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>__yard.inspect().sleepBody.visible);
// Visitor's dream hides but never modifies server sleep, then restores its appearance.
await click('#dream-archive');await click('[data-dream-id="2"]');await page.waitForFunction(()=>__yard.inspect().sleepDream.active);assert.equal(await page.evaluate(()=>__beznogimState.action.ends),snapshot.action.ends);assert.equal(await page.locator('#resident-history').isVisible(),false);await click('#exit-dream');await page.waitForFunction(()=>__yard.inspect().dreamId===null&&__yard.inspect().sleepBody.visible);
if(mobile)await click('.history-toggle');await page.waitForFunction(()=>document.querySelector('.history-list').children.length>0);assert.equal(await page.locator('.history-entry').count(),2);await click('[data-filter="actions"]');assert.equal(await page.locator('.history-entry').count(),1);assert.equal(await page.locator('.history-entry').getAttribute('data-type'),'wait');await click('.history-close');
// Current sleep expires at the server's time, even with the old snapshot still loaded.
await emit({server_time:t+8*3600+1,heartbeat:t+8*3600+1});await page.waitForFunction(()=>!__yard.inspect().sleepBody.visible);await emit({action:null,resident_status:'thinking'});await page.waitForFunction(()=>__yard.inspect().resident.action===null);assert.deepEqual((await snap()).resident.position,snapshot.position);
// Stress reusable pillow across snapshots, no geometry churn.
const nextTime=t+8*3600+2,nextSleep={...snapshot.action,started:nextTime,ends:nextTime+8*3600};
await emit({server_time:nextTime,heartbeat:nextTime,action:nextSleep,resident_status:'sleeping'});await page.waitForFunction(()=>__yard.inspect().sleepBody.visible);const geos=(await snap()).gpuGeometries;
for(let i=0;i<8;i++){await emit({action:null});await page.waitForFunction(()=>!__yard.inspect().sleepBody.visible);await emit({action:nextSleep});await page.waitForFunction(()=>__yard.inspect().sleepBody.visible);}assert.equal((await snap()).gpuGeometries,geos);
assert.equal(errors.length,0,errors.join('\n'));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth||document.documentElement.scrollHeight>innerHeight),false);
fs.writeFileSync(`${captureDir}/sleep-body-${name}.json`,JSON.stringify({passed:true,fixture:true,notProduction:true,checks:['real accept/SSE snapshot','8-hour deadline read-only','sandbox mode isolation','reload preserves controller action','dream returns to sleeping body','history wait/filter/collapse intact','server offset expiration','8 alternating states stable GPU'],geos,errors},null,2));console.log('PASS sleep/history transport fixture',name);await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
